apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: valkey-credentials
  namespace: prod
spec:
  encryptedData:
    VALKEY_PASSWORD: AgB37...encrypted_payload...
  template:
    metadata:
      name: valkey-credentials
      namespace: prod
